name: Sync Figma Variables v2

on:
  workflow_dispatch:
    inputs:
      fileKey:
        description: 'Figma File Key'
        required: true
        type: string

jobs:
  sync-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Figma Variables (bash)
        run: |
          chmod +x .github/scripts/fetch-figma-variables.sh
          .github/scripts/fetch-figma-variables.sh \
            "$FIGMA_ACCESS_TOKEN" \
            "${{ inputs.fileKey }}"
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          FIGMA_API_BASE: https://api.figma.com/v1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'feat: update design tokens from Figma'
          commit-message: 'feat: update design tokens from Figma'
          branch: feat/update-design-tokens
          delete-branch: true
          add-paths: |
            FigmaDemoGithub/tokens.json
          body: |
            Auto-generated PR from Figma variables sync