name: Sync Figma Variables

on:
  workflow_dispatch:
    inputs:
      fileKey:
        description: 'Figma File Key'
        required: true
        type: string

jobs:
  sync-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CLI dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq yq

      - name: Run Figma sync script
        working-directory: ${{ github.workspace }}
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          FIGMA_FILE_KEY:    ${{ inputs.fileKey }}
          FIGMA_API_BASE:    https://api.figma.com/v1
        run: |
          ./.github/scripts/fetch-figma-variables-v2.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'feat: update design tokens from Figma'
          commit-message: 'feat: update design tokens from Figma'
          branch: feat/update-design-tokens
          delete-branch: true
          add-paths: |
            FigmaDemoGithub/tokens.json
          body: |
            Auto-generated PR from Figma variables sync